[versions]
androidGradlePlugin = "8.7.1"
kotlin = "2.2.21"
coreKtx = "1.13.1"
lifecycleRuntimeKtx = "2.8.7"
activityKtx = "1.9.3"
appcompat = "1.7.0"
material = "1.13.0"
constraintLayout = "2.1.4"
junit4 = "4.13.2"
androidxJunit = "1.2.1"
espressoCore = "3.6.1"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
